name: diabetes_web_app
description: Web app for diabetes prediction & history
publish_to: "none"
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_secure_storage: ^8.1.0
  # bump this to the latest:
  fl_chart: ^0.71.0



dev_dependencies:
  flutter_test:
    sdk: flutter
